// generated by tools/gen_onnx_api.py from vendor/onnxruntime_c_api.h; do not edit by hand
pub const ORT_API_VERSION: u32 = 22;

pub const OrtStatus = opaque {};
pub const OrtEnv = opaque {};
pub const OrtSession = opaque {};
pub const OrtSessionOptions = opaque {};
pub const OrtRunOptions = opaque {};
pub const OrtAllocator = opaque {};
pub const OrtMemoryInfo = opaque {};
pub const OrtValue = opaque {};
pub const OrtTensorTypeAndShapeInfo = opaque {};
pub const OrtTypeInfo = opaque {};
pub const OrtKernelInfo = opaque {};
pub const OrtKernelContext = opaque {};
pub const OrtThreadingOptions = opaque {};
pub const OrtArenaCfg = opaque {};
pub const OrtPrepackedWeightsContainer = opaque {};
pub const OrtCustomOpDomain = opaque {};
pub const OrtCustomOp = opaque {};

pub const ORTCHAR_T = u8;

pub const OrtLoggingFunction = *const fn (
    param: ?*anyopaque,
    severity: OrtLoggingLevel,
    category: [*:0]const u8,
    logid: [*:0]const u8,
    code_location: [*:0]const u8,
    message: [*:0]const u8,
) callconv(.c) void;

pub const OrtErrorCode = enum(c_int) {
    ok = 0, fail = 1, invalid_argument = 2, no_such_file = 3, no_model = 4,
    engine_error = 5, runtime_exception = 6, invalid_proto_buf = 7, model_loaded = 8,
    not_implemented = 9, invalid_graph = 10, ep_fail = 11,
};

pub const OrtLoggingLevel = enum(c_int) {
    verbose = 0, info = 1, warning = 2, @"error" = 3, fatal = 4,
};

pub const OrtAllocatorType = enum(c_int) { invalid = -1, device = 0, arena = 1 };

pub const OrtMemType = enum(c_int) { cpu = 0, cpu_input = -2, cpu_output = -1 };

pub const ExecutionMode = enum(c_int) { sequential = 0, parallel = 1 };

pub const GraphOptimizationLevel = enum(c_int) {
    none = 0, basic = 1, extended = 2, all = 99,
};

pub const ONNXType = enum(c_int) {
    unknown = 0, tensor = 1, sequence = 2, @"map" = 3, @"opaque" = 4, sparse_tensor = 5, optional = 6,
};

pub const ONNXTensorElementDataType = TensorElementDataType;

pub const TensorElementDataType = enum(c_int) {
    @"undefined" = 0, float = 1, uint8 = 2, int8 = 3, uint16 = 4, int16 = 5, int32 = 6,
    int64 = 7, string = 8, bool = 9, float16 = 10, double = 11, uint32 = 12, uint64 = 13,
    complex64 = 14, complex128 = 15, bfloat16 = 16,
};

pub const OrtApiBase = extern struct {
    GetApi: *const fn (version: u32) callconv(.c) ?*const OrtApi,
    GetVersionString: *const fn () callconv(.c) [*:0]const u8,
};

pub const OrtApi = extern struct {
    CreateStatus: *const fn (OrtErrorCode, [*:0]const u8) callconv(.c) ?*OrtStatus,
    GetErrorCode: *const fn (?*const OrtStatus) callconv(.c) OrtErrorCode,
    GetErrorMessage: *const fn (?*const OrtStatus) callconv(.c) [*:0]const u8,
    CreateEnv: *const fn (OrtLoggingLevel, [*:0]const u8, *?*OrtEnv) callconv(.c) ?*OrtStatus,
    CreateEnvWithCustomLogger: *const fn (OrtLoggingFunction, ?*anyopaque, OrtLoggingLevel, [*:0]const u8, *?*OrtEnv) callconv(.c) ?*OrtStatus,
    EnableTelemetryEvents: *const fn (?*const OrtEnv) callconv(.c) ?*OrtStatus,
    DisableTelemetryEvents: *const fn (?*const OrtEnv) callconv(.c) ?*OrtStatus,
    CreateSession: *const fn (?*const OrtEnv, [*c]const ORTCHAR_T, ?*const OrtSessionOptions, *?*OrtSession) callconv(.c) ?*OrtStatus,
    CreateSessionFromArray: *const fn (?*const OrtEnv, ?*anyopaque, usize, ?*const OrtSessionOptions, *?*OrtSession) callconv(.c) ?*OrtStatus,
    Run: *const fn (?*OrtSession, ?*const OrtRunOptions, [*c][*:0]const u8, [*c]const ?*const OrtValue, usize, [*c][*:0]const u8, usize, *?*OrtValue) callconv(.c) ?*OrtStatus,
    CreateSessionOptions: *const fn (*?*OrtSessionOptions) callconv(.c) ?*OrtStatus,
    SetOptimizedModelFilePath: *const fn (?*OrtSessionOptions, [*c]const ORTCHAR_T) callconv(.c) ?*OrtStatus,
    CloneSessionOptions: *const fn (?*const OrtSessionOptions, *?*OrtSessionOptions) callconv(.c) ?*OrtStatus,
    SetSessionExecutionMode: *const fn (?*OrtSessionOptions, ExecutionMode) callconv(.c) ?*OrtStatus,
    EnableProfiling: *const fn (?*OrtSessionOptions, [*c]const ORTCHAR_T) callconv(.c) ?*OrtStatus,
    DisableProfiling: *const fn (?*OrtSessionOptions) callconv(.c) ?*OrtStatus,
    EnableMemPattern: *const fn (?*OrtSessionOptions) callconv(.c) ?*OrtStatus,
    DisableMemPattern: *const fn (?*OrtSessionOptions) callconv(.c) ?*OrtStatus,
    EnableCpuMemArena: *const fn (?*OrtSessionOptions) callconv(.c) ?*OrtStatus,
    DisableCpuMemArena: *const fn (?*OrtSessionOptions) callconv(.c) ?*OrtStatus,
    SetSessionLogId: *const fn (?*OrtSessionOptions, [*:0]const u8) callconv(.c) ?*OrtStatus,
    SetSessionLogVerbosityLevel: *const fn (?*OrtSessionOptions, c_int) callconv(.c) ?*OrtStatus,
    SetSessionLogSeverityLevel: *const fn (?*OrtSessionOptions, c_int) callconv(.c) ?*OrtStatus,
    SetSessionGraphOptimizationLevel: *const fn (?*OrtSessionOptions, GraphOptimizationLevel) callconv(.c) ?*OrtStatus,
    SetIntraOpNumThreads: *const fn (?*OrtSessionOptions, c_int) callconv(.c) ?*OrtStatus,
    SetInterOpNumThreads: *const fn (?*OrtSessionOptions, c_int) callconv(.c) ?*OrtStatus,
    CreateCustomOpDomain: *const fn ([*:0]const u8, *?*OrtCustomOpDomain) callconv(.c) ?*OrtStatus,
    CustomOpDomain_Add: *const fn (?*OrtCustomOpDomain, ?*const OrtCustomOp) callconv(.c) ?*OrtStatus,
    AddCustomOpDomain: *const fn (?*OrtSessionOptions, ?*OrtCustomOpDomain) callconv(.c) ?*OrtStatus,
    RegisterCustomOpsLibrary: *const fn (?*OrtSessionOptions, [*:0]const u8, [*c]?*anyopaque) callconv(.c) ?*OrtStatus,
    SessionGetInputCount: *const fn (?*const OrtSession, [*c]usize) callconv(.c) ?*OrtStatus,
    SessionGetOutputCount: *const fn (?*const OrtSession, [*c]usize) callconv(.c) ?*OrtStatus,
    SessionGetOverridableInitializerCount: *const fn (?*const OrtSession, [*c]usize) callconv(.c) ?*OrtStatus,
    SessionGetInputTypeInfo: *const fn (?*const OrtSession, usize, *?*OrtTypeInfo) callconv(.c) ?*OrtStatus,
    SessionGetOutputTypeInfo: *const fn (?*const OrtSession, usize, *?*OrtTypeInfo) callconv(.c) ?*OrtStatus,
    SessionGetOverridableInitializerTypeInfo: *const fn (?*const OrtSession, usize, *?*OrtTypeInfo) callconv(.c) ?*OrtStatus,
    SessionGetInputName: *const fn (?*const OrtSession, usize, ?*OrtAllocator, [*c][*:0]u8) callconv(.c) ?*OrtStatus,
    SessionGetOutputName: *const fn (?*const OrtSession, usize, ?*OrtAllocator, [*c][*:0]u8) callconv(.c) ?*OrtStatus,
    SessionGetOverridableInitializerName: *const fn (?*const OrtSession, usize, ?*OrtAllocator, [*c][*:0]u8) callconv(.c) ?*OrtStatus,
    CreateRunOptions: *const fn (*?*OrtRunOptions) callconv(.c) ?*OrtStatus,
    RunOptionsSetRunLogVerbosityLevel: *const fn (?*OrtRunOptions, c_int) callconv(.c) ?*OrtStatus,
    RunOptionsSetRunLogSeverityLevel: *const fn (?*OrtRunOptions, c_int) callconv(.c) ?*OrtStatus,
    RunOptionsSetRunTag: *const fn (?*OrtRunOptions, [*:0]const u8) callconv(.c) ?*OrtStatus,
    RunOptionsGetRunLogVerbosityLevel: *const fn (?*const OrtRunOptions, [*c]c_int) callconv(.c) ?*OrtStatus,
    RunOptionsGetRunLogSeverityLevel: *const fn (?*const OrtRunOptions, [*c]c_int) callconv(.c) ?*OrtStatus,
    RunOptionsGetRunTag: *const fn (?*const OrtRunOptions, [*c][*:0]const u8) callconv(.c) ?*OrtStatus,
    RunOptionsSetTerminate: *const fn (?*OrtRunOptions) callconv(.c) ?*OrtStatus,
    RunOptionsUnsetTerminate: *const fn (?*OrtRunOptions) callconv(.c) ?*OrtStatus,
    CreateTensorAsOrtValue: *const fn (?*OrtAllocator, [*c]const i64, usize, ONNXTensorElementDataType, *?*OrtValue) callconv(.c) ?*OrtStatus,
    CreateTensorWithDataAsOrtValue: *const fn (?*const OrtMemoryInfo, ?*anyopaque, usize, [*c]const i64, usize, ONNXTensorElementDataType, *?*OrtValue) callconv(.c) ?*OrtStatus,
    IsTensor: *const fn (?*const OrtValue, [*c]c_int) callconv(.c) ?*OrtStatus,
    GetTensorMutableData: *const fn (?*OrtValue, [*c]?*anyopaque) callconv(.c) ?*OrtStatus,
    FillStringTensor: *const fn (?*OrtValue, [*c][*:0]const u8, usize) callconv(.c) ?*OrtStatus,
    GetStringTensorDataLength: *const fn (?*const OrtValue, [*c]usize) callconv(.c) ?*OrtStatus,
    GetStringTensorContent: *const fn (?*const OrtValue, ?*anyopaque, usize, [*c]usize, usize) callconv(.c) ?*OrtStatus,
    CastTypeInfoToTensorInfo: *const fn (?*const OrtTypeInfo, *?*const OrtTensorTypeAndShapeInfo) callconv(.c) ?*OrtStatus,
    GetOnnxTypeFromTypeInfo: *const fn (?*const OrtTypeInfo, ?*ONNXType) callconv(.c) ?*OrtStatus,
    CreateTensorTypeAndShapeInfo: *const fn (*?*OrtTensorTypeAndShapeInfo) callconv(.c) ?*OrtStatus,
    SetTensorElementType: *const fn (?*OrtTensorTypeAndShapeInfo, ONNXTensorElementDataType) callconv(.c) ?*OrtStatus,
    SetDimensions: *const fn (?*OrtTensorTypeAndShapeInfo, [*c]const i64, usize) callconv(.c) ?*OrtStatus,
    GetTensorElementType: *const fn (?*const OrtTensorTypeAndShapeInfo, ?*ONNXTensorElementDataType) callconv(.c) ?*OrtStatus,
    GetDimensionsCount: *const fn (?*const OrtTensorTypeAndShapeInfo, [*c]usize) callconv(.c) ?*OrtStatus,
    GetDimensions: *const fn (?*const OrtTensorTypeAndShapeInfo, [*c]i64, usize) callconv(.c) ?*OrtStatus,
    GetSymbolicDimensions: *const fn (?*const OrtTensorTypeAndShapeInfo, [*:0]const u8, usize) callconv(.c) ?*OrtStatus,
    GetTensorShapeElementCount: *const fn (?*const OrtTensorTypeAndShapeInfo, [*c]usize) callconv(.c) ?*OrtStatus,
    GetTensorTypeAndShape: *const fn (?*const OrtValue, *?*OrtTensorTypeAndShapeInfo) callconv(.c) ?*OrtStatus,
    GetTypeInfo: *const fn (?*const OrtValue, *?*OrtTypeInfo) callconv(.c) ?*OrtStatus,
    GetValueType: *const fn (?*const OrtValue, ?*ONNXType) callconv(.c) ?*OrtStatus,
    CreateMemoryInfo: *const fn ([*:0]const u8, OrtAllocatorType, c_int, OrtMemType, *?*OrtMemoryInfo) callconv(.c) ?*OrtStatus,
    CreateCpuMemoryInfo: *const fn (OrtAllocatorType, OrtMemType, *?*OrtMemoryInfo) callconv(.c) ?*OrtStatus,
    CompareMemoryInfo: *const fn (?*const OrtMemoryInfo, ?*const OrtMemoryInfo, [*c]c_int) callconv(.c) ?*OrtStatus,
    MemoryInfoGetName: *const fn (?*const OrtMemoryInfo, [*c][*:0]const u8) callconv(.c) ?*OrtStatus,
    MemoryInfoGetId: *const fn (?*const OrtMemoryInfo, [*c]c_int) callconv(.c) ?*OrtStatus,
    MemoryInfoGetMemType: *const fn (?*const OrtMemoryInfo, ?*OrtMemType) callconv(.c) ?*OrtStatus,
    MemoryInfoGetType: *const fn (?*const OrtMemoryInfo, ?*OrtAllocatorType) callconv(.c) ?*OrtStatus,
    AllocatorAlloc: *const fn (?*OrtAllocator, usize, [*c]?*anyopaque) callconv(.c) ?*OrtStatus,
    AllocatorFree: *const fn (?*OrtAllocator, ?*anyopaque) callconv(.c) ?*OrtStatus,
    AllocatorGetInfo: *const fn (?*const OrtAllocator, *?*const OrtMemoryInfo) callconv(.c) ?*OrtStatus,
    GetAllocatorWithDefaultOptions: *const fn (*?*OrtAllocator) callconv(.c) ?*OrtStatus,
    AddFreeDimensionOverride: *const fn (?*OrtSessionOptions, [*:0]const u8, i64) callconv(.c) ?*OrtStatus,
    GetValue: *const fn (?*const OrtValue, c_int, ?*OrtAllocator, *?*OrtValue) callconv(.c) ?*OrtStatus,
    GetValueCount: *const fn (?*const OrtValue, [*c]usize) callconv(.c) ?*OrtStatus,
    CreateValue: *const fn (*?*const OrtValue, usize, ONNXType, *?*OrtValue) callconv(.c) ?*OrtStatus,
    CreateOpaqueValue: *const fn ([*:0]const u8, [*:0]const u8, ?*anyopaque, usize, *?*OrtValue) callconv(.c) ?*OrtStatus,
    GetOpaqueValue: *const fn ([*:0]const u8, [*:0]const u8, ?*const OrtValue, ?*anyopaque, usize) callconv(.c) ?*OrtStatus,
    KernelInfoGetAttribute_float: *const fn (?*const OrtKernelInfo, [*:0]const u8, [*c]f32) callconv(.c) ?*OrtStatus,
    KernelInfoGetAttribute_int64: *const fn (?*const OrtKernelInfo, [*:0]const u8, [*c]i64) callconv(.c) ?*OrtStatus,
    KernelInfoGetAttribute_string: *const fn (?*const OrtKernelInfo, [*:0]const u8, [*:0]u8, [*c]usize) callconv(.c) ?*OrtStatus,
    KernelContext_GetInputCount: *const fn (?*const OrtKernelContext, [*c]usize) callconv(.c) ?*OrtStatus,
    KernelContext_GetOutputCount: *const fn (?*const OrtKernelContext, [*c]usize) callconv(.c) ?*OrtStatus,
    KernelContext_GetInput: *const fn (?*const OrtKernelContext, usize, *?*const OrtValue) callconv(.c) ?*OrtStatus,
    KernelContext_GetOutput: *const fn (?*OrtKernelContext, usize, [*c]const i64, usize, *?*OrtValue) callconv(.c) ?*OrtStatus,
    ReleaseEnv: *const fn (?*OrtEnv) callconv(.c) void,
    ReleaseStatus: *const fn (?*OrtStatus) callconv(.c) void,
    ReleaseMemoryInfo: *const fn (?*OrtMemoryInfo) callconv(.c) void,
    ReleaseSession: *const fn (?*OrtSession) callconv(.c) void,
    ReleaseValue: *const fn (?*OrtValue) callconv(.c) void,
    ReleaseRunOptions: *const fn (?*OrtRunOptions) callconv(.c) void,
    ReleaseTypeInfo: *const fn (?*OrtTypeInfo) callconv(.c) void,
    ReleaseTensorTypeAndShapeInfo: *const fn (?*OrtTensorTypeAndShapeInfo) callconv(.c) void,
    ReleaseSessionOptions: *const fn (?*OrtSessionOptions) callconv(.c) void,
};

pub extern fn OrtGetApiBase() *const OrtApiBase;

comptime {
    const required = [_][]const u8{
        "CreateEnv",
        "CreateSessionOptions",
        "SetIntraOpNumThreads",
        "CreateSession",
        "Run",
        "GetTensorMutableData",
        "GetTensorTypeAndShape",
        "GetDimensionsCount",
        "GetDimensions",
        "CreateCpuMemoryInfo",
        "CreateTensorWithDataAsOrtValue",
        "CreateTensorAsOrtValue",
        "FillStringTensor",
        "SessionGetInputCount",
        "SessionGetOutputCount",
        "SessionGetInputName",
        "SessionGetOutputName",
        "AllocatorFree",
        "SessionGetOutputTypeInfo",
        "CastTypeInfoToTensorInfo",
        "GetTensorShapeElementCount",
        "ReleaseStatus",
        "ReleaseSession",
        "ReleaseEnv",
        "ReleaseMemoryInfo",
        "ReleaseValue",
        "ReleaseSessionOptions",
        "ReleaseTypeInfo",
        "ReleaseTensorTypeAndShapeInfo",
    };
    for (required) |name| {
        if (!@hasField(OrtApi, name)) @compileError("OrtApi missing field: " ++ name);
    }
}
