
import re

HEADER = "vendor/onnxruntime_c_api.h"
OUT = "src/model/onnx_api.zig"

src = open(HEADER).read()
start = src.index("struct OrtApi {")
end = src.index("};", start)
body = src[start:end]

PRIMS = {
    "void": "void", "int": "c_int", "int32_t": "i32", "int64_t": "i64",
    "uint32_t": "u32", "uint64_t": "u64", "size_t": "usize",
    "float": "f32", "double": "f64", "char": "u8", "bool": "bool",
    "int8_t": "i8", "uint8_t": "u8", "int16_t": "i16", "uint16_t": "u16",
}

def find_matching(s, i):
    depth = 0
    for j in range(i, len(s)):
        if s[j] == "(": depth += 1
        elif s[j] == ")":
            depth -= 1
            if depth == 0: return j
    return None

def split_args(s):
    args, depth, cur = [], 0, ""
    for ch in s:
        if ch == "," and depth == 0:
            args.append(cur.strip()); cur = ""
        else:
            if ch == "(": depth += 1
            if ch == ")": depth -= 1
            cur += ch
    if cur.strip(): args.append(cur.strip())
    return [a for a in args if a and a != "void"]

def map_type(decl):
    d = decl
    d = re.sub(r"\b_(In|Out|Inout)_\w+_?\([^)]*\)", "", d)
    d = re.sub(r"\b_[A-Za-z]\w*_\b", "", d)
    is_const = "const" in d
    d = re.sub(r"\bconst\b", "", d).strip()
    d = re.sub(r"\bstruct\b", "", d).strip()
    d = re.sub(r"\benum\b", "", d).strip()
    d = re.sub(r"[A-Za-z_]\w*\s*\[[^\]]*\]", "", d).strip()
    tokens = d.split()
    if len(tokens) >= 2 and re.fullmatch(r"[A-Za-z_]\w*", tokens[-1] or ""):
        d = " ".join(tokens[:-1])
    stars = d.count("*")
    base = d.replace("*", "").strip()
    base = PRIMS.get(base, base)
    if stars == 0:
        return base
    if base == "u8":
        return ("[*c]" * (stars - 1)) + ("[*:0]const u8" if is_const else "[*:0]u8")
    if base == "void":
        return "[*c]" * (stars - 1) + "?*anyopaque"
    if base.startswith("Ort") or base.startswith("ONNX"):
        if stars == 1:
            return ("?*const " if is_const else "?*") + base
        if stars == 2:
            return "*?" + ("*const " if is_const else "*") + base
        return "[*c]" * (stars - 2) + "*?" + ("*const " if is_const else "*") + base
    return "[*c]" * stars + ("const " if is_const else "") + base

fields = []
i = 0
n = len(body)
ret_re = re.compile(r"([A-Za-z_0-9\s\*]+?)\(ORT_API_CALL\*\s*(\w+)\)\s*\(")
api2_re = re.compile(r"ORT_API2_STATUS\(\s*(\w+)\s*,")
cls_re = re.compile(r"ORT_CLASS_RELEASE\(\s*(\w+)\s*\)")
while i < n:
    m = ret_re.match(body, i)
    if m:
        ret, name = m.group(1).strip(), m.group(2)
        close = find_matching(body, m.end() - 1)
        if close is None: i = m.end(); continue
        args = body[m.end():close]
        fields.append((map_type(ret), name, [map_type(x) for x in split_args(args)]))
        i = close + 1
        continue
    m3 = cls_re.match(body, i)
    if m3:
        name = "Release" + m3.group(1)
        fields.append(("void", name, [f"?*Ort{m3.group(1)}"]))
        i = m3.end()
        continue
    m2 = api2_re.match(body, i)
    if m2:
        name = m2.group(1)
        open_paren = body.index("(", m2.start())
        close = find_matching(body, open_paren)
        if close is None: i = m2.end(); continue
        raw_args = split_args(body[open_paren+1:close])[1:]
        fields.append(("?*OrtStatus", name, [map_type(x) for x in raw_args]))
        i = close + 1
        continue
    i += 1

names = [f[1] for f in fields]
cut = max(
    names.index("ReleaseValue"),
    names.index("ReleaseSessionOptions"),
    names.index("ReleaseTypeInfo"),
    names.index("ReleaseTensorTypeAndShapeInfo"),
) + 1
required = ["CreateEnv","CreateSessionOptions","SetIntraOpNumThreads","CreateSession","Run",
            "GetTensorMutableData","GetTensorTypeAndShape","GetDimensionsCount","GetDimensions",
            "CreateCpuMemoryInfo","CreateTensorWithDataAsOrtValue","CreateTensorAsOrtValue",
            "FillStringTensor","SessionGetInputCount","SessionGetOutputCount","SessionGetInputName",
            "SessionGetOutputName","AllocatorFree","SessionGetOutputTypeInfo","CastTypeInfoToTensorInfo",
            "GetTensorShapeElementCount","ReleaseStatus","ReleaseSession","ReleaseEnv","ReleaseMemoryInfo","ReleaseValue",
            "ReleaseSessionOptions","ReleaseTypeInfo","ReleaseTensorTypeAndShapeInfo"]
assert all(w in names[:cut] for w in required)
assert len(names) == len(set(names))

L = []
L.append("// generated by tools/gen_onnx_api.py from " + HEADER + "; do not edit by hand")
L.append("pub const ORT_API_VERSION: u32 = 22;")
L.append("")
for op in ["OrtStatus","OrtEnv","OrtSession","OrtSessionOptions","OrtRunOptions","OrtAllocator",
           "OrtMemoryInfo","OrtValue","OrtTensorTypeAndShapeInfo","OrtTypeInfo","OrtKernelInfo",
           "OrtKernelContext","OrtThreadingOptions","OrtArenaCfg","OrtPrepackedWeightsContainer",
           "OrtCustomOpDomain","OrtCustomOp"]:
    L.append(f"pub const {op} = opaque {{}};")
L.append("")
L.append("pub const ORTCHAR_T = u8;")
L.append("")
L.append("pub const OrtLoggingFunction = *const fn (")
L.append("    param: ?*anyopaque,")
L.append("    severity: OrtLoggingLevel,")
L.append("    category: [*:0]const u8,")
L.append("    logid: [*:0]const u8,")
L.append("    code_location: [*:0]const u8,")
L.append("    message: [*:0]const u8,")
L.append(") callconv(.c) void;")
L.append("")
L.append("pub const OrtErrorCode = enum(c_int) {")
L.append("    ok = 0, fail = 1, invalid_argument = 2, no_such_file = 3, no_model = 4,")
L.append("    engine_error = 5, runtime_exception = 6, invalid_proto_buf = 7, model_loaded = 8,")
L.append("    not_implemented = 9, invalid_graph = 10, ep_fail = 11,")
L.append("};")
L.append("")
L.append("pub const OrtLoggingLevel = enum(c_int) {")
L.append('    verbose = 0, info = 1, warning = 2, @"error" = 3, fatal = 4,')
L.append("};")
L.append("")
L.append("pub const OrtAllocatorType = enum(c_int) { invalid = -1, device = 0, arena = 1 };")
L.append("")
L.append("pub const OrtMemType = enum(c_int) { cpu = 0, cpu_input = -2, cpu_output = -1 };")
L.append("")
L.append("pub const ExecutionMode = enum(c_int) { sequential = 0, parallel = 1 };")
L.append("")
L.append("pub const GraphOptimizationLevel = enum(c_int) {")
L.append("    none = 0, basic = 1, extended = 2, all = 99,")
L.append("};")
L.append("")
L.append("pub const ONNXType = enum(c_int) {")
L.append('    unknown = 0, tensor = 1, sequence = 2, @"map" = 3, @"opaque" = 4, sparse_tensor = 5, optional = 6,')
L.append("};")
L.append("")
L.append("pub const ONNXTensorElementDataType = TensorElementDataType;")
L.append("")
L.append("pub const TensorElementDataType = enum(c_int) {")
L.append('    @"undefined" = 0, float = 1, uint8 = 2, int8 = 3, uint16 = 4, int16 = 5, int32 = 6,')
L.append("    int64 = 7, string = 8, bool = 9, float16 = 10, double = 11, uint32 = 12, uint64 = 13,")
L.append("    complex64 = 14, complex128 = 15, bfloat16 = 16,")
L.append("};")
L.append("")
L.append("pub const OrtApiBase = extern struct {")
L.append("    GetApi: *const fn (version: u32) callconv(.c) ?*const OrtApi,")
L.append("    GetVersionString: *const fn () callconv(.c) [*:0]const u8,")
L.append("};")
L.append("")
L.append("pub const OrtApi = extern struct {")
for ret, name, args in fields[:cut]:
    sig = ", ".join(args)
    L.append(f"    {name}: *const fn ({sig}) callconv(.c) {ret},")
L.append("};")
L.append("")
L.append("pub extern fn OrtGetApiBase() *const OrtApiBase;")
L.append("")
L.append("comptime {")
L.append("    const required = [_][]const u8{")
for w in required:
    L.append(f'        "{w}",')
L.append("    };")
L.append("    for (required) |name| {")
L.append('        if (!@hasField(OrtApi, name)) @compileError("OrtApi missing field: " ++ name);')
L.append("    }")
L.append("}")

open(OUT, "w").write("\n".join(L) + "\n")
print("generated", OUT, "fields:", cut)
